### ISSUE TITLE
Strange issue with Fabric Copper and WTHIT

### ISSUE THREAD

**Issue by Raven-dreams** [NemoNotFound/NemosCopper#1]
I've been running tests all morning trying to narrow down what is causing the error in the image.  It started after I put the new version of WTHIT in last night.  
![2024-12-09_03 42 53](https://github.com/user-attachments/assets/3d0068a0-0741-4200-9687-2945b772d1e5)

I have a very small mod pack of only 25 mods.  Have gone through adding each back into a test pack one by one.  And every time I add in your copper mod and WTHIT together, this error comes up.  Either one by themselves works just fine, but together there is something not working right. 

This is the most recent log file I've got as well with the two in there, I can't seem to figure out where its going wrong.  Was wondering what it is. 

[latest.log](https://github.com/user-attachments/files/18063136/latest.log)

It doesn't give the error in creative mode, but seems to only happen in survival mode.

And this is the log file with only your copper mod and WTHIT.

[latest.log](https://github.com/user-attachments/files/18063290/latest.log)

I'm stumped

**Comment by NemoNotFound** [comment]
Strange indeed! I will take a look, once I have the time. Thanks for reporting!

**Comment by NemoNotFound** [comment]
I took a first look, might be a compatibility issue

**Comment by Raven-dreams** [comment]
Hey no worries, I've tested it with your food mod only so far (as in with the food but not the copper) and it worked fine, no idea about any of your other ones, since i've not tried them all together.  but so far it just looks like something is odd between the copper and WTHIT pairing.  

As it is your copper is the only one i've found updated and usable for 1.21.4 at this time, and was enjoying it a lot tell we added WTHIT last night.

**Comment by NemoNotFound** [comment]
I'm glad, you enjoyed it! It's most likely only an issue with Nemo's Copper, I'll take a look to make it compatible :D

**Comment by NemoNotFound** [comment]
I think I know how to fix it, will let you know, when I do it later!

**Comment by Raven-dreams** [comment]
Oh thank you very much, very apricated.  Copper tools/armor/weapons is one of my fav style of mods to be honest.

**Comment by NemoNotFound** [comment]
Oh nice :D

If you have any suggestion for copper stuff, feel free to share! (I still have many things in mind, which I'll add in the future

**Comment by Raven-dreams** [comment]
As for suggestions, only thing I can think of is just give copper as another option in place of Iron for the normal stuff Iron can make (i.e. Lanterns, bars, hoppers etc.)  I know that would take a bit of time and work, have to make all the images and make sure the code makes the items work properly.

**Comment by NemoNotFound** [comment]
Exactly what's already planned :D

**Comment by NemoNotFound** [comment]
Tested it and it works. Will update it soon

**Comment by NemoNotFound** [comment]
Update 1.1.1 should fix it, please confirm and let me know

**Comment by Raven-dreams** [comment]
Sweet, tested it both with just WTHIT, and with all the other mods I was using.  Both came up just fine.

**Comment by NemoNotFound** [comment]
Great, will close this tickte then. Enjoy!
